### ISSUE TITLE
requirements.txt should have numpy in it!

### ISSUE THREAD

**Issue by theconsultant** [AbstractGeek/comic-scraper#2]
First time I ran the script I got an error:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/bin/comic-scraper", line 9, in <module>
    load_entry_point('comic-scraper==0.5', 'console_scripts', 'comic-scraper')()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pkg_resources/__init__.py", line 558, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2682, in load_entry_point
    return ep.load()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2355, in load
    return self.resolve()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2361, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/comic_scraper/comic_scraper.py", line 12, in <module>
    from numpy import arange

Which went away once I pip installed numpy!

**Comment by AbstractGeek** [comment]
Fixed! Thanks :+1:
